version: '3'
services:
  #process layer
  
  telegram_wrapper:
    build: ./process_services_layer/telegram_wrapper
    ports:
    - "5000:80"
  
  register_user:
    build: ./process_services_layer/register_user
    ports:
    - "5001:80"

  #business layer

  search_flight:
    build: ./business_services_layer/search_flight
    ports:
    - "5100:80"

  #adapters layer

  route_adapter:
    build: ./adapter_services_layer/route_adapter
    ports:
    - "5200:80"

  user_adapter:
    build: ./adapter_services_layer/user_adapter
    ports:
    - "5201:80"

  flight_adapter:
    build: ./adapter_services_layer/flight_adapter
    ports:
    - "5202:80"

  user-flight_adapter:
    build: ./adapter_services_layer/user-flight_adapter
    ports:
    - "5203:80"

  #data layer

  user_db:
    build: ./data_services_layer/user_db
    ports:
    - "5300:5432"
