version: '3'
services:
  #process layer
  
  telegram_wrapper:
    build: ./process_services_layer/telegram_wrapper
    ports:
    - "5000:80"
  
  register_user:
    build: ./process_services_layer/register_user
    ports:
    - "5001:80"

  #business layer


  #adapters layer

  route_adapter:
    build: ./adapter_services_layer/route_adapter
    ports:
    - "5200:80"

  user_adapter:
    build: ./adapter_services_layer/user_adapter
    ports:
    - "5201:80"

  #data layer

  user_db:
    build: ./data_services_layer/user_db
    ports:
    - "5300:5432"
