version: '3'
services:
  #process layer
  
  telegram_wrapper:
    build: ./process_services_layer/telegram_wrapper
    ports:
    - "5000:80"

  #business layer


  #adapters layer

  route_adapter:
    build: ./adapter_services_layer/route_adapter
    ports:
    - "5100:80"

  #data layer
