swagger: "2.0"
info:
  version: "1.0.0"
  title: "Route adapter"
paths:
  /:
    post:
      summary: "Calculates the route time and distance between two points"
      consumes:
        - application/json
      produces:
      - "application/json"
      parameters:
      - in: body
        name: params
        description: The parameters of the request.
        schema:
          $ref: '#/definitions/Params'
        required: true
      responses:
        200:
          description: "Ok"
          schema:
            $ref: "#/definitions/Result"
        400:
          description: "No routes available!"

definitions:
  Params:
    type: "object"
    properties:
      startLat:
        description: "Starting latitude"
        type: "number"
        format: "float"
      startLon:
        description: "Starting longitude"
        type: "number"
        format: "float"
      endLat:
        description: "Ending latitude"
        type: "number"
        format: "float"
      endLon:
        description: "Ending longitude"
        type: "number"
        format: "float"
      mean:
        type: "string"
        description: "Mean of transport"
        enum:
        - "car"
        - "foot"
        - "cycle"
  Result:
    type: "object"
    properties:
      distance:
        type: "number"
        format: "float"
        description: "Distance between the two points in meters"
      duration:
        type: "number"
        format: "float"
        description: "Duration of the movement in seconds"